name: Build Push jama_rstudio v3.6.3

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag jamamel/jama_rstudio:3.6.3
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PW }} | docker login -u ${{ secrets.DOCKERHUB_USR }} --password-stdin
    
    - name: Push the tagged Docker image
      run: docker push jamamel/jama_rstudio:3.6.3
